---
/**:
  helmoro_motor_commands:
    ros__parameters:
      # Motor Parameters
      motor_address_left: 128
      motor_address_left: 129
      motor_baudrate: 115200
      # Encoder REsolution for Actuators
      encoder_resolution: 2797 #qcpr
      # Integral Factor
      ki_factor: 0.4
      # Robot Dimensions
      wheel_spacing_x: 0.115 #m
      wheel_spacing_y: 0.195 #m
      wheel_diameter: 0.09 #m
      # Velocity Constraints
      max_lin_vel: 1.1 #m/s
      max_ang_vel: 10.5 #rad/s