name: Run Tests

on:
  push:
    branches:
      - '**'
      - '!humble'
      - '!jazzy'

jobs:
  colcon-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /home/ws
    container: 
      image: ghcr.io/helbling-technik/helmoro-software-ros2:${{ github.ref_name }}-latest
      
    steps:
      - name: Run tests
        shell: bash
        run: |
          source entrypoint.sh
          colcon test

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
            name: colcon-logs
            path: /home/ws/log
            if-no-files-found: error
        if: always() # upload the logs even when the build fails
